<?php

namespace ContainerSH5VkDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oyg1UmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oyg1Um_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oyg1Um_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BookController::borrow' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\BookController::createBook' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\BookController::deleteBook' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\BookController::listing' => ['privates', '.service_locator.VqxhnIj', 'get_ServiceLocator_VqxhnIjService', true],
            'App\\Controller\\BookController::updateBook' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ClientController::createclient' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ClientController::deleteclient' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ClientController::listing' => ['privates', '.service_locator.VqxhnIj', 'get_ServiceLocator_VqxhnIjService', true],
            'App\\Controller\\ClientController::showClient' => ['privates', '.service_locator.GHSVmsZ', 'get_ServiceLocator_GHSVmsZService', true],
            'App\\Controller\\ClientController::updateclient' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\BookController:borrow' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\BookController:createBook' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\BookController:deleteBook' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\BookController:listing' => ['privates', '.service_locator.VqxhnIj', 'get_ServiceLocator_VqxhnIjService', true],
            'App\\Controller\\BookController:updateBook' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ClientController:createclient' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ClientController:deleteclient' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ClientController:listing' => ['privates', '.service_locator.VqxhnIj', 'get_ServiceLocator_VqxhnIjService', true],
            'App\\Controller\\ClientController:showClient' => ['privates', '.service_locator.GHSVmsZ', 'get_ServiceLocator_GHSVmsZService', true],
            'App\\Controller\\ClientController:updateclient' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\BookController::borrow' => '?',
            'App\\Controller\\BookController::createBook' => '?',
            'App\\Controller\\BookController::deleteBook' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::listing' => '?',
            'App\\Controller\\BookController::updateBook' => '?',
            'App\\Controller\\ClientController::createclient' => '?',
            'App\\Controller\\ClientController::deleteclient' => '?',
            'App\\Controller\\ClientController::listing' => '?',
            'App\\Controller\\ClientController::showClient' => '?',
            'App\\Controller\\ClientController::updateclient' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BookController:borrow' => '?',
            'App\\Controller\\BookController:createBook' => '?',
            'App\\Controller\\BookController:deleteBook' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:listing' => '?',
            'App\\Controller\\BookController:updateBook' => '?',
            'App\\Controller\\ClientController:createclient' => '?',
            'App\\Controller\\ClientController:deleteclient' => '?',
            'App\\Controller\\ClientController:listing' => '?',
            'App\\Controller\\ClientController:showClient' => '?',
            'App\\Controller\\ClientController:updateclient' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
