<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWiCoxKH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWiCoxKH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWiCoxKH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWiCoxKH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWiCoxKH\App_KernelDevDebugContainer([
    'container.build_hash' => 'WiCoxKH',
    'container.build_id' => 'cc72ac52',
    'container.build_time' => 1645093904,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWiCoxKH');
